#!/usr/bin/perl -w

#Usage: ./iraw2png <width> <height> < <imgsrc.raw> > <imgdst.png>
$w = shift || 240;
$h = shift || 320;
$pixels = $w * $h;

open OUT, "|pnmtopng" or die "Can't pipe pnmtopng: $!\n";
 
printf OUT "P6%d %d\n255\n", $w, $h;

while ((read STDIN, $raw, 2) and $pixels--) {
   $short = unpack('S', $raw);
   print OUT pack("C3",
      #($short & 0x8000) >> 15,	#a #oran oranti 256/32 = 8
      (((($short & 0x7C00) >> 10) * 8) + 0) % 256,	#r
      (((($short & 0x03E0) >> 5) * 8) + 0) % 256,	#g
      (((($short & 0x1F) >> 0) * 8) + 0) % 256);	#b
}

close OUT;
